//! Generates `man/hog.1` from the clap grammar with `clap_mangen`.
//!
//! The page is not written by hand: NAME, SYNOPSIS, DESCRIPTION and OPTIONS
//! come straight out of `hog::Cli::command()`, and COMMANDS is walked off the
//! same `clap::Command` tree. Only the sections a grammar cannot know —
//! EXIT STATUS, ENVIRONMENT, FILES, the template rules, the migration notes —
//! are supplied here as roff.

use std::io::Write as _;

use clap::CommandFactory as _;
use roff::{Roff, bold, italic, roman};

/// The date that lands in the `.TH` line. Fixed rather than `today`, so that
/// regenerating without a content change produces no diff.
const DATE: &str = "2026-09-12";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out = std::env::args().nth(1).ok_or("usage: hog-mangen <OUT.1>")?;

    // The `version` string is resolved by build.rs (git describe / $HOG_VERSION)
    // and so differs on every machine. It cannot be removed — `-v` is declared
    // with `ArgAction::Version`, which clap asserts against — so instead it is
    // kept out of the page: `.source()` below replaces the `.TH` field that
    // would have carried it, and the VERSION section is written by hand.
    let cmd = hog::Cli::command()
        .name("hog")
        .display_name("hog")
        .about("read JSON logs line by line and print them for humans")
        .long_about(DESCRIPTION.trim());

    let man = clap_mangen::Man::new(cmd.clone())
        .title("HOG")
        .section("1")
        .date(DATE)
        .source("hog")
        .manual("hog manual");

    let mut page: Vec<u8> = Vec::new();
    man.render_title(&mut page)?;
    man.render_name_section(&mut page)?;
    man.render_synopsis_section(&mut page)?;
    man.render_description_section(&mut page)?;
    man.render_options_section(&mut page)?;
    commands_section(&cmd).to_writer(&mut page)?;
    for section in TAIL_SECTIONS {
        prose(section).to_writer(&mut page)?;
    }

    let mut file = std::fs::File::create(&out)?;
    file.write_all(HEADER.as_bytes())?;
    file.write_all(dedupe_preamble(&String::from_utf8(page)?).as_bytes())?;
    file.flush()?;
    eprintln!("wrote {out}");
    Ok(())
}

/// The apostrophe preamble `roff` emits at the head of every document.
///
/// Each `render_*_section` call is its own document, so the pair repeats once
/// per section. It is harmless — the definition is idempotent — but it is a
/// third of the file's control lines, and a reviewer reading a diff of a
/// generated page should not have to skip past it fifteen times.
const PREAMBLE: [&str; 2] = [r".ie \n(.g .ds Aq \(aq", r".el .ds Aq '"];

/// Keeps the first [`PREAMBLE`] and drops the repeats.
fn dedupe_preamble(page: &str) -> String {
    let mut kept = 0usize;
    let mut out = String::with_capacity(page.len());
    for line in page.lines() {
        if PREAMBLE.contains(&line) {
            if kept >= PREAMBLE.len() {
                continue;
            }
            kept += 1;
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// Comment lines above the `.TH`, so the file says how to make it again.
const HEADER: &str = concat!(
    ".\\\" Generated by clap_mangen from the clap grammar in src/cli.rs.\n",
    ".\\\" Do not edit by hand. Regenerate with:\n",
    ".\\\"   cargo run --manifest-path man/generate/Cargo.toml -- man/hog.1\n",
);

/// DESCRIPTION. Written for the page rather than taken from the `Cli` doc
/// comment, which is a note to the next maintainer about `CARGO_PKG_VERSION`.
const DESCRIPTION: &str = "\
hog reads a stream of JSON log lines and prints each one as a single readable
line: a timestamp, a level tag, the message, and the remaining fields as
key=value pairs. Nested objects are flattened into dotted keys, so
{\"grpc\":{\"code\":\"OK\"}} prints as grpc.code=OK. A line that does not start with
{ is passed through byte for byte, which keeps stack traces, build banners and
ssh diagnostics intact.

hog reads from one of two places. With no positional arguments it reads standard
input, so `tail -f app.log | hog` and `hog < app.log` work as expected. With
positional arguments it runs the command template from its config file,
substituting the arguments into it by position, and renders that command's
standard output. The template runs without a local shell.

Nothing is hidden from the output unless a config file or -e says so, and the
key order in the tail is alphabetical by default so that two lines can be
compared column by column.";

/// A section written here because no grammar contains it.
struct Section {
    heading: &'static str,
    /// Blocks in order. See [`prose`] for the markup.
    body: &'static [Block],
}

enum Block {
    /// A paragraph of running text.
    Para(&'static str),
    /// A `.TP` entry: term, then its definition.
    Item(&'static str, &'static str),
    /// Preformatted lines, indented.
    Pre(&'static str),
}

/// Turns a [`Section`] into roff.
fn prose(section: &Section) -> Roff {
    let mut roff = Roff::default();
    roff.control("SH", [section.heading]);
    for (index, block) in section.body.iter().enumerate() {
        // `.PP` straight after `.SH` is a paragraph break with no paragraph in
        // front of it; mandoc warns and drops it.
        let first = index == 0;
        match block {
            Block::Para(text) => {
                if !first {
                    roff.control("PP", []);
                }
                roff.text([roman(unwrap_lines(text))]);
            }
            Block::Item(term, text) => {
                roff.control("TP", []);
                roff.text([bold(*term)]);
                roff.text([roman(unwrap_lines(text))]);
            }
            Block::Pre(text) => {
                if !first {
                    roff.control("PP", []);
                }
                roff.control("RS", ["4"]);
                roff.control("nf", []);
                roff.text([roman(text.trim_end())]);
                roff.control("fi", []);
                roff.control("RE", []);
            }
        }
    }
    roff
}

/// Joins the hard-wrapped source text back into paragraphs; roff does its own
/// filling, and a source line break would otherwise become a line break.
fn unwrap_lines(text: &str) -> String {
    text.trim()
        .lines()
        .map(str::trim)
        .collect::<Vec<_>>()
        .join(" ")
}

/// COMMANDS, walked off the same `clap::Command` the OPTIONS section came from.
///
/// `clap_mangen`'s own subcommands section emits cross-references to pages that
/// do not exist (`hog-config(1)`), and it stops at the first level — which is
/// where every `hog config` verb lives. This walks the whole tree instead and
/// prints each leaf as the line a user would type.
fn commands_section(cmd: &clap::Command) -> Roff {
    let mut roff = Roff::default();
    roff.control("SH", ["COMMANDS"]);
    roff.text([roman(unwrap_lines(
        "A subcommand name is matched before the first positional argument, so an
         argument that is spelled like one is passed after --: `hog -- config api`.",
    ))]);
    walk(&mut roff, cmd, "hog");
    roff
}

fn walk(roff: &mut Roff, cmd: &clap::Command, prefix: &str) {
    let mut subs: Vec<_> = cmd.get_subcommands().filter(|s| !s.is_hide_set()).collect();
    subs.sort_by_key(|s| s.get_name().to_owned());

    for sub in subs {
        if sub.get_name() == "help" {
            continue;
        }
        let path = format!("{prefix} {}", sub.get_name());
        let operands = operands(sub);

        roff.control("TP", []);
        let mut line = vec![bold(path.clone())];
        if !operands.is_empty() {
            line.push(roman(" "));
            line.push(italic(operands));
        }
        roff.text(line);
        if let Some(about) = sub.get_about() {
            roff.text([roman(about.to_string())]);
        }

        walk(roff, sub, &path);
    }
}

/// The positional part of a subcommand's usage, e.g. `<FIELD>...`.
fn operands(cmd: &clap::Command) -> String {
    cmd.get_positionals()
        .filter(|arg| !arg.is_hide_set())
        .map(|arg| {
            let name = arg
                .get_value_names()
                .and_then(|names| names.first().map(ToString::to_string))
                .unwrap_or_else(|| arg.get_id().to_string().to_uppercase());
            let many = if matches!(
                arg.get_num_args(),
                Some(range) if range.max_values() > 1
            ) {
                "..."
            } else {
                ""
            };
            if arg.is_required_set() {
                format!("<{name}>{many}")
            } else {
                format!("[{name}]{many}")
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

const TAIL_SECTIONS: &[&Section] = &[
    &INPUT_MODES,
    &TEMPLATE,
    &EXCLUDING,
    &CONFIGURATION,
    &EXIT_STATUS,
    &ENVIRONMENT,
    &FILES,
    &EXAMPLES,
    &COMPLETIONS,
    &NOTES,
    &VERSION,
    &SEE_ALSO,
];

const INPUT_MODES: Section = Section {
    heading: "INPUT MODES",
    body: &[
        Block::Para(
            "The mode is chosen by the presence of positional arguments. There is no flag
             for it, and no other heuristic.",
        ),
        Block::Item(
            "arguments given",
            "The config file's command template runs, with the arguments substituted into
             it. Standard input is not read. If the config sets no template, the built-in
             `echo {@}` runs, so a brand-new install shows where its arguments go.",
        ),
        Block::Item(
            "no arguments, standard input is a pipe or a file",
            "Standard input is rendered.",
        ),
        Block::Item(
            "no arguments, standard input is a terminal",
            "The configured command runs. With no configured command hog prints its help
             and exits 2, rather than waiting forever for JSON to be typed at it.",
        ),
        Block::Para(
            "--dry-run always takes the command branch: it answers `what would you run?`,
             which is not a question about standard input.",
        ),
    ],
};

const TEMPLATE: Section = Section {
    heading: "COMMAND TEMPLATE",
    body: &[
        Block::Para(
            "The `command` key in the config file is a command line. hog splits it into
             argv by shell quoting rules and executes it directly: there is no local
             shell, so a redirection or a pipe written outside quotes becomes a literal
             argument. Inside quotes it is the remote shell's business, and works.",
        ),
        Block::Pre(
            "command = \"ssh -tt -o ServerAliveInterval=15 {0} \\\n\
             \x20            'docker logs -f --since 1h bpam-{1}-1'\"",
        ),
        Block::Para("Placeholders are substituted into the split words:"),
        Block::Item(
            "{0}, {1}, ...",
            "The first, second, ... positional argument. Indices must run from {0} with
             no gaps: a template using {0} and {2} is rejected when the config is read.",
        ),
        Block::Item(
            "{@}",
            "Every argument no index took. With N the highest index used, {@} is
             arguments N+1 onwards; with no indexed placeholder it is all of them. It
             expands to separate argv words in place, and to nothing at all when there
             are none, like \"$@\" in a shell. It must be a whole word of its own: a
             second {@}, or a template writing bpam-{@}-1, is rejected.",
        ),
        Block::Item(
            "{}, {{0}}, {{@}}",
            "Literal. A bare {} is left alone so that `find -exec {} \\;` and
             `docker --format '{{.Names}}'` survive; {{0}} produces a literal {0}.",
        ),
        Block::Para(
            "Arity is checked. A template with {0} and {1} needs exactly two arguments;
             with {@} it accepts any number; with both it has a floor and no ceiling.
             `hog --help` prints the configured template, its arity and an example.",
        ),
        Block::Para(
            "Arguments are validated before substitution, never quoted. hog cannot know
             whether an argument lands in a word the remote shell will split again,
             as in 'docker logs bpam-{1}-1', or in a bare argv entry, as in
             -l app={1}, where it would not. Quoting is therefore not solvable in the
             general case, and hog does not try. Instead only
             [A-Za-z0-9._:/@-] is accepted, at most 256 bytes per argument. That covers
             docker, Kubernetes and systemd names, user@host and host:port, and rejects
             every character that could break out of a word at either level.",
        ),
        Block::Para(
            "An argument beginning with - passes that whitelist by construction, and
             reaches the spawned program's argv as a flag of that program. See NOTES.",
        ),
    ],
};

const EXCLUDING: Section = Section {
    heading: "EXCLUDING FIELDS",
    body: &[
        Block::Para(
            "An exclusion is a dotted path, matched on segment boundaries, and it prunes
             the whole subtree under it. `grpc` hides grpc.code and
             grpc.request.deadline; it does not hide grpcStatus, which is a different
             key that merely starts with the same letters. That is why exclusions are
             dotted paths rather than globs or substrings: a glob such as grpc.* invites
             exactly the grpcStatus mistake, while subtree pruning already covers the
             case it was wanted for.",
        ),
        Block::Item("hog", "The list from the config file."),
        Block::Item("hog -e foo", "The list from the config file, plus foo."),
        Block::Item("hog -E", "Nothing is hidden."),
        Block::Item(
            "hog -E -e foo",
            "Exactly foo; this is how the file's list is replaced.",
        ),
        Block::Para(
            "-e is repeatable and comma-separated: `-e a,b -e c` excludes a, b and c.
             `hog config exclude add` and `hog config exclude rm` change the persistent
             list in the file, keeping its comments.",
        ),
    ],
};

const CONFIGURATION: Section = Section {
    heading: "CONFIGURATION",
    body: &[
        Block::Para(
            "The first of these that exists wins; the files are never merged. Values
             layer as built-in defaults, then the config file, then command-line flags.",
        ),
        Block::Item(
            "--config PATH",
            "Used as given. A missing file is an error.",
        ),
        Block::Item("$HOG_CONFIG", "The same, from the environment."),
        Block::Item(
            "$XDG_CONFIG_HOME/hog/config.toml",
            "Or $HOME/.config/hog/config.toml when XDG_CONFIG_HOME is unset. This holds
             on macOS too: hog is a developer CLI that belongs in dotfiles next to
             ~/.config/gh, and the same file has to work unchanged on the Linux hosts it
             logs into.",
        ),
        Block::Para(
            "There is no implicit ./hog.toml and no walk up the directory tree. The
             config names a command that hog executes, so picking one up from the
             current directory would make `git clone && cd && hog prod api` a way to run
             someone else's command. Use --config ./hog.toml when that is what is
             wanted.",
        ),
        Block::Para(
            "`hog config init` writes a commented starter file. An unknown key is a
             warning naming the line, never an error, so a config written for a newer
             hog still runs here.",
        ),
        Block::Item("exclude", "Array of dotted paths to hide. Top-level key."),
        Block::Item("command", "The command template. Top-level key."),
        Block::Item(
            "[fields] ts, level, msg",
            "Candidate key names for the three columns; the first one present in a line
             wins, decided per line.",
        ),
        Block::Item(
            "[output] time_format",
            "A jiff strftime pattern such as %H:%M:%S, or `raw` to print the timestamp
             byte for byte, or `none` to drop the column.",
        ),
        Block::Item(
            "[output] time_zone",
            "`local` (default), `utc`, or an IANA name such as Europe/Moscow.",
        ),
        Block::Item("[output] color", "`auto`, `always` or `never`."),
        Block::Item(
            "[output] sort_keys",
            "true sorts the tail alphabetically; false keeps the JSON order.",
        ),
        Block::Item(
            "[output] key_colors",
            "Hex colours for key names. A key's colour is FNV-1a(name) modulo the
             palette length, so it is stable across runs and machines.",
        ),
        Block::Item(
            "[output.levels]",
            "Maps a producer's own level spellings onto the ones hog knows, e.g.
             \"30\" = \"info\" for pino and bunyan.",
        ),
        Block::Para(
            "command and exclude are top-level keys and must appear above the first
             [table] header: a bare key written after [output] would be read as
             output.command.",
        ),
    ],
};

const EXIT_STATUS: Section = Section {
    heading: "EXIT STATUS",
    body: &[
        Block::Item("0", "Success; the input stream ended."),
        Block::Item(
            "1",
            "Runtime error: the config, the template, or a rejected argument.",
        ),
        Block::Item(
            "2",
            "Usage error, including a bare hog on a terminal with nothing configured.",
        ),
        Block::Item(
            "127",
            "The template's first word is not an executable in PATH.",
        ),
        Block::Item(
            "141",
            "hog's own standard output was closed, as by `| head`.",
        ),
        Block::Item(
            "n",
            "Otherwise, the exit status of the command hog ran. A command killed by a signal reports 128 plus the signal number, as a shell would.",
        ),
        Block::Para(
            "A command that fails also prints one line to standard error naming the
             status and how many lines had already been rendered, so that an ssh
             connection dropping after 1423 lines does not read like the log ending.",
        ),
    ],
};

const ENVIRONMENT: Section = Section {
    heading: "ENVIRONMENT",
    body: &[
        Block::Item(
            "HOG_CONFIG",
            "Config file to read, unless --config is given.",
        ),
        Block::Item(
            "XDG_CONFIG_HOME, HOME",
            "Where the default config file is looked for.",
        ),
        Block::Item("NO_COLOR", "Set to any value to disable colour."),
        Block::Item(
            "CLICOLOR_FORCE",
            "Set to any value to force colour on, even when not writing to a terminal.",
        ),
        Block::Item(
            "TERM",
            "Consulted to decide how much colour the terminal can take. True-colour palettes are downgraded to 256 colours where needed.",
        ),
        Block::Item(
            "VISUAL, EDITOR",
            "The editor `hog config edit` launches, VISUAL first.",
        ),
    ],
};

const FILES: Section = Section {
    heading: "FILES",
    body: &[Block::Item(
        "$XDG_CONFIG_HOME/hog/config.toml",
        "The config file. `hog config path` prints the one that is actually read.",
    )],
};

const EXAMPLES: Section = Section {
    heading: "EXAMPLES",
    body: &[
        Block::Para("Render a file, hiding two noisy fields:"),
        Block::Pre("hog -e trace_id,serviceName < app.log"),
        Block::Para("Follow a local service:"),
        Block::Pre("journalctl -u api -f -o cat | hog"),
        Block::Para("Store a template, then use it:"),
        Block::Pre(
            "hog config command set \"ssh -tt -o ServerAliveInterval=15 {0} \\\n\
             \x20 'docker logs -f --since 1h bpam-{1}-1'\"\n\
             hog prod api",
        ),
        Block::Para("See what that would run, without connecting:"),
        Block::Pre("hog --dry-run prod api"),
        Block::Para(
            "Pass a variable tail through to the far end. The -- is needed because hog's
             own flags still parse after the positional arguments, so an unknown --since
             would be a usage error rather than a value:",
        ),
        Block::Pre(
            "hog config command set \"ssh -tt {0} 'docker logs -f {@}'\"\n\
             hog prod -- --since 30m --tail 200",
        ),
    ],
};

const COMPLETIONS: Section = Section {
    heading: "SHELL COMPLETIONS",
    body: &[
        Block::Para(
            "`hog completions SHELL` writes a completion script to standard output. SHELL
             is one of bash, elvish, fish, powershell or zsh. The command is hidden from
             --help because it is run once at install time, not day to day.",
        ),
        Block::Pre(
            "hog completions zsh  > \"${fpath[1]}/_hog\"\n\
             hog completions bash > /etc/bash_completion.d/hog\n\
             hog completions fish > ~/.config/fish/completions/hog.fish",
        ),
    ],
};

const SEE_ALSO: Section = Section {
    heading: "SEE ALSO",
    body: &[
        Block::Para("jq(1), ssh(1), ssh_config(5), journalctl(1)"),
        Block::Para("https://github.com/chaindead/hog"),
    ],
};

const NOTES: Section = Section {
    heading: "NOTES",
    body: &[
        Block::Item(
            "Arguments that begin with a dash",
            "- is on the argument whitelist, because host names and image tags contain
             it. An argument such as --tail therefore passes validation and arrives in
             the spawned program's argv as a flag of that program, not of hog. There is
             no privilege escalation in this: no shell is involved, the argument stays
             one argv word, and the program was already named by your own config file.
             But the flags a template's program accepts are part of what a caller can
             reach, so a template should not be pointed at a program whose flags you
             would not want supplied. Pass such an argument after --, since hog's own
             parser would otherwise read it as a hog flag: `hog prod -- --tail`.",
        ),
        Block::Item(
            "-tt and ServerAliveInterval in the starter template",
            "Both are load-bearing, and both are easy to delete as noise. -tt gives the
             remote command a pty: without one, a container that is quiet produces no
             traffic, ssh never sees EPIPE after hog exits, and `docker logs -f` keeps
             running on the remote host after every Ctrl-C. -o ServerAliveInterval=15
             replaces ssh's default of 0: without it a VPN that drops leaves hog waiting
             forever with no output and no error.",
        ),
        Block::Item(
            "Migrating from hulog",
            "hog prints the timestamp in the machine's time zone, because time_zone
             defaults to `local`. hulog kept the offset written in the input string, so
             a log stamped with Z printed as UTC wherever it was read. The rendered
             digits will therefore differ. Set time_zone = \"utc\" in [output], or pass
             --timezone utc, to get hulog's numbers back.",
        ),
    ],
};

const VERSION: Section = Section {
    heading: "VERSION",
    body: &[Block::Para(
        "`hog --version` prints the release tag the binary was built from, or
         `dev` with the commit and a dirty marker for a local build.",
    )],
};
